sudo: false

os:
  - linux

branches:
  only:
    - master
language: python

env:
  matrix:
    - TASK=lint
    - TASK=coverage
    - TASK=test

script:
    - make -f Makefile.travis $TASK

python:
  - "2.7"
  - "3.4"
  - "pypy"
